### ISSUE TITLE
Vitals Measurements 

### ISSUE THREAD

**Issue by xpes** [gmedina-de/webapp23-group5#2]
Few doubts Regarding the Vitals Measurements 
(1) should it be a mandatory value or an optional one
(2) if mandatory how is the app able to gather vitals information, is it through another service or it has to be entered manually
(3) if it has to be manually entered then it wouldn't be a viable option since vitals are a real-time information measured over a period of time.
(4) should the vitals data be assigned to an activity so that the user gets better information regarding the average temperature, blood pressure, spo2 reading during the period of activity.

**Comment by gmedina-de** [comment]
Hello !

1. Vitals are not a value but a kind of measurement that one can take, just like scale or tape measurements. The only optional argument is a comment.
2. In the context of this course only entering data manually via web form. 
3. Well, one could argue the same about other kind of measurements such as weight. Take as example Google Fit or other known services: they also allow entering blood pressure, heart rate and temperature manually.
4. No. That may complicate things unnecessarily.

**Comment by xpes** [comment]
While adding any measurements is it mandatory to add all the measurements at once or user can add any one kind of measurement like scale or tape at a single instance

**Comment by gmedina-de** [comment]
Since measurements can be updated afterwards and for example maybe only blood pressure but no temperature was measured (or viceversa) actually no field is mandatory in the measurements but date and time.
